algoritmo "Contar_Regressiva"
// Função : Contar de 10 a 0.
// Autor : Oscar LuIS Yopan
// Data : 25/01/2022
var
C : inteiro
inicio
EscrevaL ("--------------------------------------------------------------------")
EscrevaL ("                        Contagem Regressiva                         ")
EscrevaL ("--------------------------------------------------------------------")
C <- 11
Enquanto (C > 0) faca
         C <- (C - 1)
         EscrevaL (C)
FimEnquanto
EscrevaL ("Fim da Contagem Regressiva")
EscrevaL ("--------------------------------------------------------------------")
fimalgoritmo
