algoritmo "Contagem_Personalisada"
// Função : Contar até o número escolhido pelo usuario.
// Autor : Oscar Luis Yopan
// Data : 25/01/2022
var
C, N : inteiro
inicio
EscrevaL ("--------------------------------------------------------------------")
EscrevaL ("                             Contagem                               ")
EscrevaL ("--------------------------------------------------------------------")
Escreva ("Contar até: ")
Leia(N)
C <- 0
Enquanto (C < N) Faca
         C <- (C + 1)
         EscrevaL (C)
FimEnquanto
EscrevaL ("Fim da Contagem")
EscrevaL ("--------------------------------------------------------------------")
// Seção de Comandos 
fimalgoritmo
