algoritmo "Conte_Ate_100"
// Função : Contar de 0 a 100 e mostrar na tela, contando de 10 em 10.
// Autor : Oscar Luis Yopan
// Data : 25/01/2022
// Seção de Declarações
var
C, C2 : inteiro
inicio
EscrevaL ("--------------------------------------------------------------------")
EscrevaL ("                           Conte até 100                            ")
EscrevaL ("--------------------------------------------------------------------")
C <- 0
Enquanto (C < 100) Faca
   C <- ( C + 10)
   EscrevaL (C)
FimEnquanto
EscrevaL ("Fim da Contagem!")
EscrevaL ("--------------------------------------------------------------------")
// Seção de Comandos
fimalgoritmo
