algoritmo "Ola_Nome"
// Função : 2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boasvindas
// para ela:
// Ex:
// Qual é o seu nome? João da Silva
// Olá João da Silva, é um prazer te conhecer!
// Autor :
// Data : 15/02/2022
// Seção de Declarações 
var
N : Caractere
inicio
EscrevaL ("Qual seu nome? ")
Leia (N)
Escreva ("Olá ", N, ", é um prazer te conhecer!")
fimalgoritmo
