algoritmo "Contagem_10-3"
// Função :39) Faça um algoritmo que mostre na tela a seguinte contagem:
//10 9 8 7 6 5 4 3 Acabou!
// Autor : Oscar Luis Yopan
// Data : 27/01/2022
var
C : inteiro
inicio
EscrevaL ("--------------------------------------------------------------------")
EscrevaL ("                              Contagem                              ")
EscrevaL ("--------------------------------------------------------------------")
C <- 11
Enquanto (C > 3) faca
      C <- (C - 1)
      EscrevaL (C)
FimEnquanto
EscrevaL ("-----------------------")
EscrevaL ("Acabou!")
EscrevaL ("--------------------------------------------------------------------")
fimalgoritmo
