algoritmo "semnome"
// Função : 4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
// entre eles.
// Ex:
// Digite um valor: 8
// Digite outro valor: 5
// A soma entre 8 e 5 é igual a 13.
// Autor : Oscar Luis Yopan
// Data : 15/02/2022
var
N1, N2, S : Inteiro
inicio
Escreva ("Numero 1: ")
Leia (N1)
Escreva ("Numero 2: ")
Leia (N2)
S <- N1 + N2
Escreva ("A Soma entre ", N1, " e ", N2, " é: ", S)
fimalgoritmo
