algoritmo "Exercic 5"
// Função : Aluno
// Autor : Oscar
// Data : 13/09/2021
// Seção de Declarações 
var
aluno: caractere
n1, n2, m: real
inicio
escreva ("Insira Nome do Aluno: ")
leia (aluno)
escreva ("Insira a Nota pra primeira prova: ")
leia (n1)
escreva ("Insira a Nota pra primeira prova: ")
leia (n2)
m <-  ((n1 + n2)/2)
escreva (aluno, " Sua Media no Bimestre é: ", m)
// Seção de Comandos
fimalgoritmo
