algoritmo "Contagem_6-11"
// Função : 38) Escreva um programa que mostre na tela a seguinte contagem:
//6 7 8 9 10 11 Acabou!
// Autor : Oscar Luis Yopan
// Data : 27/01/2022
var
C : inteiro
inicio
EscrevaL ("--------------------------------------------------------------------")
EscrevaL ("                              Contagem                              ")
EscrevaL ("--------------------------------------------------------------------")
C <- 5
Enquanto (C < 11) faca
      C <- (C + 1)
      EscrevaL (C)
FimEnquanto
EscrevaL ("-----------------------")
EscrevaL ("Acabou!")
EscrevaL ("--------------------------------------------------------------------")
fimalgoritmo
