algoritmo "Some_7"
// Função : 48) Faça um programa que leia 7 números inteiros e no final mostre o somatório
//entre eles.
// Autor : Oscar Luis Yopan
// Data : 27/01/2022
var
C, T, N : inteiro
inicio
EscrevaL ("--------------------------------------------------------------------")
EscrevaL ("                           Some 7 Numerais                         ")
EscrevaL ("--------------------------------------------------------------------")
C <- 1
T <- 0
Enquanto (C <= 7) faca
         Escreva ("Valor ", C, " :")
         Leia (N)
         C <- (C + 1)
         T <- (T + N)
FimEnquanto
EscrevaL ("-----------------------------------------")
EscrevaL ("A soma total dos Valores é: ", T)
EscrevaL ("--------------------------------------------------------------------")
fimalgoritmo
