algoritmo "Numeros_Pares"
// Função : Faça um algoritmo que mostre quais são numeros pares.
// Autor : Oscar Luis Yopan
// Data : 31/01/2022
var
C, N : inteiro
inicio
EscrevaL ("------------------------------------")
EscrevaL ("           Numeros Pares            ")
EscrevaL ("------------------------------------")
Escreva ("Pares Até: ")
Leia (N)
Para C <- 0 Ate N Passo 2 Faca
     EscrevaL (C)
FimPara
EscrevaL ("Acabou!")
EscrevaL ("------------------------------------")
fimalgoritmo
