algoritmo "Combinações"
// Função : Faça um programa que Combine os 1, 2 e 3.
// Autor : Oscar Luis Yopan
// Data : 31/01/2022
var
C, C2 : Inteiro
inicio
EscrevaL ("-------------------------------")
EscrevaL ("         Combine 1.2.3         ")
EscrevaL ("-------------------------------")
Para C <- 1 Ate 3 Faca
     Para C2 <- 1 Ate 3 Faca
      EscrevaL (C, C2)
     FimPara
FimPara
EscrevaL ("-------------------------------")
fimalgoritmo
