algoritmo "Contar_Ate_10"
// Função : Faça um algoritmo que conte de 1- 10 usando "Para"
// Autor : Oscar Luis Yopan
// Data : 31/01/2022
var
C : inteiro
inicio
EscrevaL ("------------------------------------")
EscrevaL ("          Contar 1 até 10           ")
EscrevaL ("------------------------------------")
Para C <- 10 Ate 1 Passo -1 Faca
     EscrevaL (C)
FimPara
EscrevaL ("Acabou!")
EscrevaL ("------------------------------------")
fimalgoritmo
